### ISSUE TITLE
Release the first Alpha1 version with Netty 5.0.0.Alpha5

### ISSUE THREAD

**Issue by pderop** [netty-contrib/codec-multipart#19]
@chrisvest @normanmaurer,

Hi Norman, Chris,

What do you think about releasing the first **Alpha1** version for this codec-multipart module based on Netty **5.0.0.Alpha5** ?

- the following PRs have been merged for this candidate [5.0.0.Alpha1](https://github.com/netty-contrib/codec-multipart/milestone/1?closed=1) release;

- and the following issues are planned for the next [5.0.0.Alpha2](https://github.com/netty-contrib/codec-multipart/milestone/2) release. I'll work first on the #18 issue once the Alpha1 will be released.

**Comment by chrisvest** [comment]
@pderop Sounds good. You should be able to run the release workflow yourself. Let me know if that doesn't work.

**Comment by pderop** [comment]
@chrisvest ,

I confirm it worked and I've been able to release:

https://repo.maven.apache.org/maven2/io/netty/contrib/netty-codec-multipart/5.0.0.Alpha1/

thank you !
